language: python

python: 
  - 3.7

node_js:
  - 12.16.3
cache: npm

git:
  depth: false

install:
  - npm ci
  - pip install -r requirements.txt

jobs:
  include:
    - stage: Build and Push to Github Pages
      before_script:
        - git checkout "${TRAVIS_BRANCH}"
        - python test.py
        - cd src
        - python preprocess.py
        - python citations.py
        - cd ..
      script:
        - npm test
        - npm run build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local_dir: dist
        on:
          branch: master
      after_script:
        - git config --global user.email "travis@travis-ci.com"
        - git config --global user.name "Travis CI"
        - git status
        # Remove existing "origin"
        - git remote rm origin
        # Add new "origin" with access token in the git URL for authentication
        - git remote add origin https://ballaneypranav:${GITHUB_TOKEN}@github.com/igembitsgoa/wiki.git > /dev/null 2>&1
        - git status
        - git add *.*
        - git add dist
        - 'git commit -m "Travis: Build and deploy to Github Pages" -m "[skip ci]"'
        - git status
        - git fetch
        - git log --oneline --decorate -10
        - git push origin "${TRAVIS_BRANCH}" -f

    - stage: Deploy to iGEM
      if: commit_message =~ /iGEM-deploy/
      script:
        - git checkout "${TRAVIS_BRANCH}"
        - git config --global user.email "travis@travis-ci.com"
        - git config --global user.name "Travis CI"
        - python igem-wikisync.py
        - cat upload_map.yml
        - git status
        # Remove existing "origin"
        - git remote rm origin
        # Add new "origin" with access token in the git URL for authentication
        - git remote add origin https://ballaneypranav:${GITHUB_TOKEN}@github.com/igembitsgoa/wiki.git > /dev/null 2>&1
        - git status
        - git add *.*
        - git add igem
        - git add dist
        - 'git commit -m "Travis: Build and deploy to iGEM" -m "[skip ci]"'
        - git status
        - git branch --list
        - git fetch
        - git log --oneline --decorate -10
        - git push origin "${TRAVIS_BRANCH}" -f