language: python

python: 
  - 3.7

node_js:
  - 12.16.3
cache: npm

git:
  depth: false

install:
  - npm ci
  - pip install -r requirements.txt

before_script:
  - git checkout "${TRAVIS_BRANCH}"
  - python test.py
  - cd src
  - python preprocess.py
  - python citations.py
  - cd ..

script:
  - npm test
  - npm run build

after_script:
  - git branch --show-current
  - git add .
  - git status

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master

