language: python

python: 
  - 3.7

node_js:
  - 12.16.3
cache: npm

git:
  depth: false

before_install:
  # - bash list_modified_files.sh

install:
  - npm ci
  - pip install -r requirements.txt

before_script:
  - python test.py
  - cd src
  - python preprocess.py
  - python citations.py

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master