language: python

python: 
  - 3.7

node_js:
  - 12.16.3
cache: npm

git:
  depth: false

install:
  - npm ci
  - pip install -r requirements.txt

jobs:
  include:
    - stage: Build and Push to Github Pages
      before_script:
        # Git setup
        - git checkout "${TRAVIS_BRANCH}"
        - git config --global user.email "travis@travis-ci.com"
        - git config --global user.name "Travis CI"
      script:
        # Custom tests and preprocessing
        - sh github.io_fix.sh # This changes URLs for github.io
        - python test.py
        - python citations.py
        - python preprocess.py
        - python nav.py
        - npm test
        - npm run build
        # Add new "origin" with access token in the git URL for authentication
        - git remote rm origin
        - git remote add origin https://ballaneypranav:${GITHUB_TOKEN}@github.com/igembitsgoa/wiki.git > /dev/null 2>&1
        - git status
        - git add src/citations/cache.yml
        - 'git commit -m "Travis: Build and deploy to Github" -m "[skip ci]" || echo "No changes to commit"'
        - git push origin "${TRAVIS_BRANCH}" -f
      deploy:
        skip-cleanup: true
        provider: pages
        github-token: $GITHUB_TOKEN
        local_dir: dist
        on:
          branch: master

    - stage: Build and Deploy to iGEM
      if: commit_message =~ /iGEM-deploy/
      before_script:
        # Git setup
        - git checkout "${TRAVIS_BRANCH}"
        - git config --global user.email "travis@travis-ci.com"
        - git config --global user.name "Travis CI"
      script:
        # Custom tests and preprocessing
        - python test.py
        - python citations.py
        - python preprocess.py
        - python nav.py
        - npm test
        - npm run build
        # Push to iGEM
        - pip install igem-wikisync
        - python wikisync.py
        # Print upload map in case pushing back to Github doesn't work
        - cat upload_map.yml
        - git status
        # Remove existing "origin"
        - git remote rm origin
        # Add new "origin" with access token in the git URL for authentication
        - git remote add origin https://ballaneypranav:${GITHUB_TOKEN}@github.com/igembitsgoa/wiki.git > /dev/null 2>&1
        - git status
        - git add upload_map.yml wikisync.log dist igem
        - 'git commit -m "Travis: Build and deploy to iGEM" -m "[skip ci]"'
        - git status
        - git branch --list
        - git fetch
        - git log --oneline --decorate -10
        - git push origin "${TRAVIS_BRANCH}" -f

notifications:
  email:
    on_success: never
    on_failure: always
